"""Provider de rules para Cursor."""

from pathlib import Path

from ..contracts.provider import GenerationReport, PromptTemplate


PROMPT_METADATA: dict[str, tuple[str, str]] = {
    "prd": ("PRD generation assistant", "PRD Generator"),
    "techespec": ("Technical specification assistant", "TechSpec Generator"),
    "tasks": ("Task breakdown assistant", "Task Breakdown Generator"),
    "verify": ("Implementation verification assistant", "Verification Assistant"),
    "context-sync": ("Context synchronization assistant", "Context Sync Assistant"),
}


class CursorSkillProvider:
    """Gera `.cursor/rules/*.mdc` a partir dos prompts do projeto."""

    name = "Cursor"

    def generate(
        self,
        project_dir: Path,
        prompts: list[PromptTemplate],
        overwrite: bool = False,
    ) -> GenerationReport:
        created_files: list[Path] = []
        skipped_files: list[Path] = []

        for prompt in prompts:
            description, title = self._metadata_for(prompt.stem)
            rule_file = project_dir / ".cursor" / "rules" / f"{prompt.stem}.mdc"
            rule_file.parent.mkdir(parents=True, exist_ok=True)

            if rule_file.exists() and not overwrite:
                skipped_files.append(rule_file)
                continue

            content = (
                "---\n"
                f"description: {description}\n"
                "globs:\n"
                '  - "**/*"\n'
                "alwaysApply: false\n"
                "---\n\n"
                f"# Skill: {title}\n\n"
                f"{prompt.content}"
            )
            rule_file.write_text(content, encoding="utf-8")
            created_files.append(rule_file)

        return GenerationReport(
            provider_name=self.name,
            created_files=created_files,
            skipped_files=skipped_files,
        )

    @staticmethod
    def _metadata_for(prompt_stem: str) -> tuple[str, str]:
        if prompt_stem in PROMPT_METADATA:
            return PROMPT_METADATA[prompt_stem]

        readable = prompt_stem.replace("-", " ").title()
        return ("Prompt rule generated by NexusSpec", readable)
